apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-endpoint
  labels:
    app: health
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health
  template:
    metadata:
      labels:
        app: health
    spec:
      containers:
        - image: ozacas/health-endpoint-arm64:v0.1.12
          name: health
          ports:
            - containerPort: 8000
              name: http
